import { Selector } from 'testcafe';

fixture `AMARILLOS`
    .page `https://dev.ingenes.com/`;

/***********************************************************
*                                                           *  
*                      AMARILLO INGRIG                      *
*                                                           *
************************************************************/

test(`INGRIGAmarillo1999`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next span').withText('Con mi pareja hombre'))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Más de 4 años').nth(4))
        .click(Selector('#__next p').withText('1 vez'))
        .click(Selector('#__next p').withText('Tengo 1 hijo'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_Digusa0217@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
         .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Estados Unidos').nth(6))
        .typeText('#field-207', '10001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Houston, Texas'))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(6))
        .typeText('#field-209', 'KEVIN FAMILIA')

        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next div').withText('Continuar').nth(4))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))

        .click(Selector('#__next div').withText('Vehículo propio').nth(6))
        .click(Selector('#__next div').withText('Empresaria').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next div').withText('Casada').nth(6))
        .typeText('#field-210', 'prueba')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '01')
        .typeText('#field-214', '11')
        .typeText('#field-215', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(6))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'));
});

test(`INGRIGAmarillo1993`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next span').withText('Con mi pareja hombre'))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Más de 4 años').nth(4))
        .click(Selector('#__next p').withText('1 vez'))
        .click(Selector('#__next p').withText('Tengo 1 hijo'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_Digusa0218@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
         .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Estados Unidos').nth(6))
        .typeText('#field-207', '10001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Houston, Texas'))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(6))
        .typeText('#field-209', 'KEVIN FAMILIA')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Vehículo propio').nth(6))
        .click(Selector('#__next div').withText('Empresaria').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next div').withText('Casada').nth(6))
         .typeText('#field-210', 'prueba')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '01')
        .typeText('#field-214', '11')
        .typeText('#field-215', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(6))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'));
});
/***********************************************************
*                                                          *  
*                      AMARILLO INGRIG                 *
*                                                          *
************************************************************/

//INGRIG MEDICAMENTOS PARA OVULAR
test(`INGRIGAmarilloMedicamentos`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next span').withText('Con mi pareja hombre'))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next div').withText('He tomado medicamentos para ovular (coitos program').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Más de 4 años').nth(4))
        .click(Selector('#__next p').withText('1 vez'))
        .click(Selector('#__next p').withText('Tengo 1 hijo'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'pruebaEsp')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Sólo estoy investigando opciones').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_Digusa0219@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
         .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Estados Unidos').nth(6))
        .typeText('#field-207', '10001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Houston, Texas'))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(6))
        .typeText('#field-209', 'KEVIN FAMILIA')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Vehículo propio').nth(6))
        .click(Selector('#__next div').withText('Empresaria').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next div').withText('Casada').nth(6))
       .typeText('#field-210', 'prueba')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '01')
        .typeText('#field-214', '11')
        .typeText('#field-215', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(6))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'));
});

//INGRIG FECUNDACION IN VITRO
test(`INGRIGAmarilloInVitro`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next span').withText('Con mi pareja hombre'))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next div').withText('Me realizaron algún tipo de Fecundación in Vitro (').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Más de 4 años').nth(4))
        .click(Selector('#__next p').withText('1 vez'))
        .click(Selector('#__next p').withText('Tengo 1 hijo'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'pruebaEsp')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Sólo estoy investigando opciones').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_Digusa0220@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
         .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Estados Unidos').nth(6))
        .typeText('#field-207', '10001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Houston, Texas'))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(6))
        .typeText('#field-209', 'KEVIN FAMILIA')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Vehículo propio').nth(6))
        .click(Selector('#__next div').withText('Empresaria').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next div').withText('Casada').nth(6))
         .typeText('#field-210', 'prueba')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '01')
        .typeText('#field-214', '11')
        .typeText('#field-215', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(6))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'));
});

//INGRIG INSEMINACION ARTIFICIAL
test(`INGRIGAmarilloInseminacionAr`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next span').withText('Con mi pareja hombre'))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next div').withText('Me realizaron una o más Inseminaciones Artificiale').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Más de 4 años').nth(4))
        .click(Selector('#__next p').withText('1 vez'))
        .click(Selector('#__next p').withText('Tengo 1 hijo'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'pruebaEsp')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Sólo estoy investigando opciones').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_Digusa0221@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Estados Unidos').nth(6))
        .typeText('#field-207', '10001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Houston, Texas'))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(6))
        .typeText('#field-209', 'KEVIN FAMILIA')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Vehículo propio').nth(6))
        .click(Selector('#__next div').withText('Empresaria').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next div').withText('Casada').nth(6))
         .typeText('#field-210', 'prueba')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '01')
        .typeText('#field-214', '11')
        .typeText('#field-215', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(6))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'));
});
//INGRIG SIN TRATAMIENTO
test('INGRID AZUL 1986', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))    
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(7))
        .click(Selector('#__next div').withText('Con mi pareja hombre').nth(7))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Más de 5 años').nth(4))
        .click(Selector('#__next div').withText('Más de 4 años').nth(4))
        .click(Selector('#__next div').withText('1 vez').nth(4))
        .click(Selector('#__next p').withText('Tengo 1 hijo'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'PRUEBA')
        .pressKey('tab')
        .typeText('#field-5', 'PRUEBA')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(4))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_Digusa0222@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Estados Unidos').nth(6))
        .typeText('#field-207', '10001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Houston, Texas'))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))

        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(6))
        .typeText('#field-209', 'KEVIN FAMILIA')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next div').withText('Empresaria').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next div').withText('Casada').nth(7))
        .typeText('#field-210', 'PRUEBA')
        .typeText('#field-211', 'PRUEBA')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '04')
        .typeText('#field-214', '11')
        .typeText('#field-215', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(6))
        .click(Selector('#__next div').withText('Alto').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
});