import { Selector } from 'testcafe';

fixture `INTERMEDIOS ON DIGITAL`
    .page `https://dev.ingenes.com/`;

/***********************************************************
*                                                          *  
*                      INTERMEDIO Edith                    *
*                                                          *
************************************************************/
//Eva MEDICAMENTOS SIN TRATAMIENTO 1999 local intermedio
test(`EdithIntermedio1999`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next div').withText('Sin pareja').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Entre 1 y 3 años'))
        .click(Selector('#__next div').withText('Entre 1 y 3 años').nth(4))
        .click(Selector('#__next p').withText('1 vez'))
        .click(Selector('#__next p').withText('Tengo 3 o más hijos'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0134@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('México').nth(5))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '77001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Mi familiar trabaja en una empresa que tiene benef'))
        .typeText('#field-209', 'kevin familia')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Vehículo propio').nth(6))
        .click(Selector('#__next div').withText('Comerciante').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next button').withText('Continuar'));
});
//Edith MEDICAMENTOS SIN TRATAMIENTO 1993 local Blanco
test(`EdithIntermedio1993`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next div').withText('Sin pareja').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Lo antes posible').nth(4))
        .click(Selector('#__next p').withText('1 vez'))
        .click(Selector('#__next p').withText('Tengo 3 o más hijos'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0140@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '77001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))

            .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next p').withText('Google'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))

        .click(Selector('#__next div').withText('Vehículo propio').nth(6))
        .click(Selector('#__next div').withText('Comerciante').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next button').withText('Continuar'));
});

//Edith MEDICAMENTOS PARA OVULAR Foranea Blanco
test(`EdithIntermedio`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next div').withText('Sin pareja').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('He tomado medicamentos para ovular (coitos program').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Lo antes posible').nth(4))
        .click(Selector('#__next p').withText('3 veces o más'))
        .click(Selector('#__next p').withText('Tengo 3 o más hijos'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'pruebaNan')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Ya tengo un diagnóstico pero quiero una segunda op').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0141@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('México').nth(5))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '10001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))

            .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        
        .click(Selector('#__next span').withText('Mi familiar trabaja en una empresa que tiene benef'))
        .typeText('#field-209', 'kevin familia')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))

        .click(Selector('#__next div').withText('Taxi, Uber, etc.').nth(6))
        .click(Selector('#__next div').withText('Empleada profesionista').nth(6))
        .click(Selector('#__next span').withText('No'))
        .click(Selector('#__next button').withText('Continuar'));
});


//Edith FECUNDACION IN VITRO local Blanco
test(`EdithIntermedio`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next div').withText('Sin pareja').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Me realizaron algún tipo de Fecundación in Vitro (').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Entre 1 y 3 años').nth(4))
        .click(Selector('#__next p').withText('3 veces o más'))
        .click(Selector('#__next p').withText('Tengo 3 o más hijos'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'pruebaNan')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Ya tengo un diagnóstico pero quiero una segunda op').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0142@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('México').nth(5))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '77001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))

            .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next p').withText('Google'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))

        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))

        .click(Selector('#__next div').withText('Taxi, Uber, etc.').nth(6))
        .click(Selector('#__next div').withText('Empleada profesionista').nth(6))
        .click(Selector('#__next span').withText('No'))
        .click(Selector('#__next button').withText('Continuar'));
});
// // //Edith INSEMINACION ARTIFICIAL local Intermedio BIEN
test(`EdithIntermedio`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next div').withText('Sin pareja').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Me realizaron una o más Inseminaciones Artificiale').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Entre 1 y 3 años'))
        .click(Selector('#__next div').withText('Entre 1 y 3 años').nth(4))
        .click(Selector('#__next p').withText('3 veces o más'))
        .click(Selector('#__next p').withText('Tengo 3 o más hijos'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'pruebaNan')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Ya tengo un diagnóstico pero quiero una segunda op').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0138@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('México').nth(5))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '77001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next p').withText('Google'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Taxi, Uber, etc.').nth(6))
        .click(Selector('#__next div').withText('Empleada profesionista').nth(6))
        .click(Selector('#__next span').withText('No'))
        .click(Selector('#__next button').withText('Continuar'));
});
// //Edith SIN TRATAMIENTO Local 
test(`EdithIntermedioSinTratamiento`, async t => {
    await t
        .click(Selector('#__next span').withText('Femenino'))
        .click(Selector('#__next div').withText('Quiero tener un bebé').nth(6))
        .click(Selector('#__next div').withText('Sin pareja').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Más de 5 años'))
        .click(Selector('#__next div').withText('Entre 1 y 3 años').nth(4))
        .click(Selector('#__next p').withText('1 vez'))
        .click(Selector('#__next p').withText('Tengo 3 o más hijos'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '21')
        .typeText('#field-8', '11')
        .typeText('#field-9', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0143@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5516950291')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('México').nth(5))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '77001')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))

            .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next p').withText('Google'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))

        .click(Selector('#__next div').withText('Vehículo propio').nth(6))
        .click(Selector('#__next div').withText('Comerciante').nth(6))
        .click(Selector('#__next span').withText('Sí, tengo tarjeta de crédito'))
        .click(Selector('#__next button').withText('Continuar'));
});