import { Selector } from 'testcafe';

fixture `Eva Amarillo TRATAMIENTOS`
    .page `https://dev.ingenes.com/`;

/**********************
 *                                                              *
 *                     Eva Amarillo USA   Bien                    *
 *                                                              *
 **********************/
test('Eva Amarillo 1999', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja mujer').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0116@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico') 
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .click('#field-210')
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#field-213')
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1998')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
// //Bien
test('Eva Amarillo 1993', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja mujer').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1992')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0117@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .click('#field-210')
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#field-213')
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1992')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
/************************
 *                                                                  *
 *                     Esperanza Amarillo USA                      *
 *                                                                  *
 ************************/
 //BIEN
test('Eva Amarillo Medicamentos', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja mujer').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next span').withText('He tomado medicamentos para ovular (coitos program'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_017@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .click('#field-210')
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#field-213')
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1998')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
// BIEN
test('Eva Amarillo In Vitro', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja mujer').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next div').withText('Me realizaron algún tipo de Fecundación in Vitro (').nth(4))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_018@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .click('#field-210')
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#field-213')
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1998')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
// BIEN
test('Eva Amarillo Inseminación', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja mujer').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Sí, yo estoy operada').nth(6))
        .click(Selector('#__next div').withText('Me realizaron algún tipo de Fecundación in Vitro (').nth(4))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_019@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .click('#field-210')
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#field-213')
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1998')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
// BIEN
test('Eva Amarillo 1993', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja mujer').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa_0115@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('No estoy interesado'))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .click('#field-210')
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#field-213')
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});