import { Selector } from 'testcafe';

fixture `Nancy Amarillo Digital USA`
    .page `https://dev.ingenes.com/`;
/***********************************************************
*                                                           *  
*                     AMARILLO NANCY                        *
*                                                           *
************************************************************/

test('Nancy Amarillo99', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))    
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja hombre').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        // .pressKey('tab')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1999')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa001g@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        // .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1998')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
test('Nancy Amarillo93', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))    
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja hombre').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        // .click('#field-3')
        // .click('#field-3')
        // .pressKey('ctrl')
        // .pressKey('ctrl+v')
        // .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        // .pressKey('tab')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa002g@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        // .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1993')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});

/***********************************************************
*                                                           *  
*                     AMARILLO ESPERANZA                    *
*                                                           *
************************************************************/
test('Esperanza Amarillo Medicamentos', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))    
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja hombre').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('He tomado medicamentos para ovular (coitos program').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        // .click('#field-3')
        // .click('#field-3')
        // .pressKey('ctrl')
        // .pressKey('ctrl+v')
        // .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        // .pressKey('tab')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa003g@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        // .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
test('Esperanza Amarillo InVitro', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))    
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja hombre').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Me realizaron algún tipo de Fecundación in Vitro (').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        // .click('#field-3')
        // .click('#field-3')
        // .pressKey('ctrl')
        // .pressKey('ctrl+v')
        // .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        // .pressKey('tab')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa004g@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        // .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
test('Esperanza Amarillo Inseminacion', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))    
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja hombre').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Me realizaron una o más Inseminaciones Artificiale').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        // .click('#field-3')
        // .click('#field-3')
        // .pressKey('ctrl')
        // .pressKey('ctrl+v')
        // .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        // .pressKey('tab')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa005g@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        // .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});
test('Esperanza Amarillo86', async t => {
    await t
        .click(Selector('#__next div').withText('Femenino').nth(6))    
        .click(Selector('#__next p').withText('Quiero tener un bebé'))
        .click(Selector('#__next div').withText('Con mi pareja hombre').nth(6))
        .click(Selector('#__next div').withText('No').nth(8))
        .click(Selector('#__next div').withText('Ninguno').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Menos de 1 año'))
        .click(Selector('#__next p').withText('Lo antes posible'))
        .click(Selector('#__next div').withText('No').nth(4))
        // .click('#field-3')
        // .click('#field-3')
        // .pressKey('ctrl')
        // .pressKey('ctrl+v')
        // .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-3', 'x&7J^pZ!q2@rB9#w$8L')
        .click('#__next .chakra-image.css-0')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-4', 'prueba')
        // .pressKey('tab')
        .typeText('#field-5', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-7', '10')
        .pressKey('tab')
        .typeText('#field-8', '11')
        .pressKey('tab')
        .typeText('#field-9', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Quiero agendar una cita').nth(6))
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-12', 'prueba_usa006g@gmail.com')
        .click(Selector('#__next button').withText('Continuar'))
        .click('#menu-button-16 .chakra-icon.css-onkibi')
        .click('#menu-list-16-menuitem-17')
        .typeText('#field-206', '5541658945')
        .click(Selector('#__next button').withText('Continuar'))
        // .click(Selector('#__next p').withText('México'))
        .click(Selector('#__next span').withText('Estados Unidos'))
        .typeText('#field-207', '92705')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Houston, Texas').nth(7))
        .click('#email-lead')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Mi familiar trabaja en una empresa que tiene benef').nth(4))
        .typeText('#field-209', 'Ingenes Mexico')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('No').nth(6))
        .click(Selector('#__next button').withText('No, ninguno'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next p').withText('Endometriosis'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next span').withText('Vehículo propio'))
        .click(Selector('#__next span').withText('Empresaria'))
        .click('#__next .chakra-image.css-1kwjtme')
        .click(Selector('#__next div').withText('Casada').nth(6))
        .typeText('#field-210', 'prueba')
        .pressKey('tab')
        .typeText('#field-211', 'prueba')
        .click(Selector('#__next button').withText('Continuar'))
        .typeText('#field-213', '10')
        .pressKey('tab')
        .typeText('#field-214', '12')
        .pressKey('tab')
        .typeText('#field-215', '1986')
        .click(Selector('#__next button').withText('Continuar'))
        .click(Selector('#__next div').withText('Empresario/a').nth(7))
        .click(Selector('#__next p').withText('Alto'))
        .click(Selector('#__next button').withText('Continuar'))
});